### ISSUE TITLE
Avoid recompiling

### ISSUE THREAD

**Issue by chikamichi** [ANXS/nginx#10]
Hi,

I wonder whether you'd like this role avoiding recompiling nginx?

When I use it several times in a row (for instance with `vagrant provision`, because I made some changes to my stack), it always recompile nginx although this is useless in this use case.

**Comment by farridav** [comment]
Perhaps you could write out the flags nginx was compiled to into a file and diff them in the task to see if it needs recompiling... I also had the issue with the old nginx still running, and I now use a handler for killing nginx processes on each re-provision..

**Comment by farridav** [comment]
Had a spare min so i put up a PR for this, let me know if fits the bill...

**Comment by chikamichi** [comment]
Thank you @farridav
