### ISSUE TITLE
Ansible Galaxy dependency issues

### ISSUE THREAD

**Issue by farridav** [ANXS/nginx#22]
On Ansible galaxy, your roles are [no longer listed](https://galaxy.ansible.com/api/v1/users/?username=Ansibles) under `Ansibles`, I [found some](https://galaxy.ansible.com/api/v1/users/?username=pjan.vandaele) under `pjan.vandaele` are they old? im not too clear on the distinction between the roles you have here, and the ones found in https://github.com/pjan/the-ansibles/, would you care to clarify for me?

To give a working example:

```bash
$ ansible-galaxy install Ansibles.nginx
    downloading role 'nginx', owned by Ansibles
    Sorry, Ansibles.nginx was not found on galaxy.ansible.com.
```
And when i use the `pjan.vandaele.nginx` version, i get unmet dependency issues:

```bash
$ ansible-galaxy install pjan.vandaele.nginx [...]
$ ansible-playbook --syntax-check my_playbook.yml 

playbook: my_playbook.yml

ERROR: cannot find role in [...]/Ansibles.hostname or [...]
```
I guess the dependencies will need updating [here](https://github.com/Ansibles/nginx/blob/master/meta/main.yml#L17) and anywhere else... 

Feel free to point me in the right direction if ive misunderstood something..

Thanks in advance, and thanks for the great contributions!

**Comment by farridav** [comment]
@pjan sure, feel free to add me to the maintainers group, my time is usually quite scattered, but when im working on ops, I can keep my eyes open and pitch in where possible

**Comment by soupdiver** [comment]
@pjan I would also be willing to help to maintain and further development of the roles

**Comment by pjan** [comment]
@farridav @soupdiver I'll add you both to the list of maintainers. I'm living a couple of hours ahead of you both, and @otakup0pe is behind.

I suggest we use gitter to talk, since asynchrony will be unavoidable (timezones & life), and this way we'll keep our inboxes a bit less congested? How does that sound? Other suggestions?

**Comment by soupdiver** [comment]
@pjan I haven't used gitter so far but looks good :)
