### ISSUE TITLE
cannot find the role

### ISSUE THREAD

**Issue by tgld** [ANXS/nginx#58]
ERROR: cannot find role in /Users/lakshman/ansible-try1/roles/role/roles/ANXS.hostname
i have the downloaded role and i am running with ansible playbook command as following
\---
- hosts: web2
  roles:
    - role: nginx

and i have also set the roles-path as :
roles_path    = /Users/lakshman/ansible-try1/roles in ansible.cfg

**Comment by soupdiver** [comment]
Your path does look a bit weird.
 /Users/lakshman/ansible-try1/**roles/role/roles/**ANXS.hostname

It looks there is a `role/roles` too much

**Comment by tgld** [comment]
now i have rectified the clumsy path. now where should i place this role named "nginx".
Either in /opt/ansible/roles or create a path in ansible.cfg and place it there.

btw what is this ANXS.hostname should i change any file in the role

**Comment by soupdiver** [comment]
If your role path is ` /opt/ansible/roles` then the role should be placed in ` /opt/ansible/roles/ANXS.nginx`

**Comment by tgld** [comment]
SO THE ROLE PATH IS SAME AS WHAT YOU SAID, should i change the role name to "ANXS.nginx".

**Comment by tgld** [comment]
<img width="1280" alt="screen shot 2015-07-30 at 5 32 03 pm" src="https://cloud.githubusercontent.com/assets/6481030/8978874/f55a22c6-36e0-11e5-9ebc-1f1c85fc83b8.png">

**Comment by tgld** [comment]
i still can't understand how it takes the role. please add election of role in ready page

**Comment by soupdiver** [comment]
If you say your role path is the same as I wrote then your current setup is not correct.
As you can read on the screenshot you posted the role needs to be placed in `/Users/lakshman/ansible-try1/roles/nginx` or `/opt/local/etc/ansible/roles/nginx` and not  `/opt/ansible/roles/ANXS.nginx`

**Comment by tgld** [comment]
To be clear:
1) I have placed my roles in the default configuration . i.e /opt/local/etc/ansible/roles/ . so the role named nginx is placed here. 
<img width="1279" alt="screen shot 2015-07-30 at 5 54 49 pm" src="https://cloud.githubusercontent.com/assets/6481030/8979375/1e606a88-36e4-11e5-8393-0b655d7a5697.png">


2) If i place it under ANXS.nginx, it also gives me an error
<img width="1280" alt="screen shot 2015-07-30 at 5 57 05 pm" src="https://cloud.githubusercontent.com/assets/6481030/8979418/718a8978-36e4-11e5-9e06-a55dfe3d5e79.png">

I am quite confused, please help me with this

**Comment by soupdiver** [comment]
can you post the out put of `ls -la /opt/local/etc/ansible` and `ls -la /opt/local/etc/ansible/roles`?

**Comment by tgld** [comment]
<img width="1277" alt="screen shot 2015-07-30 at 6 04 20 pm" src="https://cloud.githubusercontent.com/assets/6481030/8979547/6fa70c70-36e5-11e5-8358-cdc1a69f233b.png">
<img width="1280" alt="screen shot 2015-07-30 at 6 03 36 pm" src="https://cloud.githubusercontent.com/assets/6481030/8979548/6fe0d324-36e5-11e5-815d-649c53e1e7b5.png">

**Comment by soupdiver** [comment]
Rename the folder to `nginx`
As you can see if the outputs before it's looking for nginx and not ANXS.nginx

**Comment by tgld** [comment]
so this is like i have created nginx dir , inside that an nginx within that all tasks, handlers,etc,.

now it gives an error like this.
<img width="1278" alt="screen shot 2015-07-30 at 6 28 36 pm" src="https://cloud.githubusercontent.com/assets/6481030/8980030/d7c4326c-36e8-11e5-9fd3-fdb286152807.png">


if i make just roles/nginx and this nginx contains all tasks, handlers. This gives me an error asking ANXS.nginx


I have worked on roles, but this gives me weird error

**Comment by soupdiver** [comment]
It's complaining that specific files can't be found. Are they present at all?

**Comment by tgld** [comment]
ya they are present

**Comment by soupdiver** [comment]
If the files are in place I don't know...
maybe try creating an empty dir from scratch. Create the playbook which includes the role in that empty dir.
Then install put all required roles in a `roles` subdir and try executing the playbook again.

I'm not totally sure what's wrong with your paths

**Comment by tgld** [comment]
ya ok thank you
