### ISSUE TITLE
httplib2 missing error, but nginx work!

### ISSUE THREAD

**Issue by soulcreate** [ANXS/nginx#70]
TASK: [Nginx | Check if nginx is available] ***********************************
failed: [loc] => {"failed": true}
msg: httplib2 is not installed

**Comment by farridav** [comment]
aha that will be because of http://docs.ansible.com/ansible/uri_module.html#requirements .. Ive put up a PR to fix this... though will need to resolve the openssl issue before getting it in https://github.com/ANXS/nginx/pull/71

**Comment by soupdiver** [comment]
#71 is green again :)

**Comment by soupdiver** [comment]
With #71 being merged can we close this one?

**Comment by farridav** [comment]
I think so @soupdiver.. Closing .. @soulcreate please reopen if needed
