### ISSUE TITLE
openssl version out of date

### ISSUE THREAD

**Issue by roscom** [ANXS/nginx#72]
# OpenSSL configuration

defaults/main.yml: 

shown as
`openssl_version: "1.0.2c"`

should be:
`openssl_version: "1.0.2e"`

**Comment by farridav** [comment]
the openssl version was bumped 5 days ago, and is reflected here https://github.com/ANXS/nginx/blob/master/defaults/main.yml#L172 .. are you seeing otherwise? If so, can you point me in the right direction and Ill see that its resolved..

**Comment by farridav** [comment]
I've been doing some additional digging, and unsurprisingly Ansible galaxy hasn't imported the newest tag of this build (its supposed to do it automatically, but hasn't, and AFAICT they have no API we can use) I've manually triggered a re-import in the interface, which should pull in 1.4.0 soon hopefully :) when I finally see it appear on https://galaxy.ansible.com/detail#/role/551 Ill update and close this issue

**Comment by farridav** [comment]
Bumped to 1.0.2f and re-imported into ansible galaxy, apologies its taken a while, been having some issues with galaxy imports.. closing
